### ISSUE TITLE
Upgrade to >3

### ISSUE THREAD

**Issue by cryptiklemur** [theY4Kman/viper#3]
Not sure if you are looking to upgrade this project at all, but an upgrade to ~3.3.0 would be awesome

**Comment by theY4Kman** [comment]
I haven't actively developed the project in months, maybe years, and neither has Anthony. But pull requests are always welcome :P

**Comment by cryptiklemur** [comment]
haha, i wouldn't even know how to do that. I've got no experience in the C's

**Comment by monokrome** [comment]
Upgrading to >3 is a big effort considering it will surely cause scripts to become deprecated, so may require some consideration on that front.
